### ISSUE TITLE
Unable to use 1.11.0 when WP_DEBUG is set to false

### ISSUE THREAD

**Issue by kmonahan** [timber/timber#2084]
Running into a strange issue where templates show a blank white screen with the latest version of Timber when WP_DEBUG is set to false in wp-config.php or left unset (which means it defaults to false). Pages return a 200 response and there are no errors displayed when WP_DEBUG is enabled. There's just nothing there.

I chased the issue down to /vendor/twig/twig/src/Environment.php and determined that if I manually set $this->debug to true in the constructor there, the site displays as expected. I'm not sure, therefore, whether this is an issue with Timber itself and what it's relying on Twig's debug settings for or a bug in the version of Twig that's bundled with Timber. (Using the version that's downloaded from wordpress.org.)

Rolling back to 1.9.x resolves the issue.
## What version of WordPress, PHP and Timber are you using?
WordPress 5.2.3, PHP 7.0, Timber 1.11.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org (fresh download today)

**Comment by timnolte** [comment]
I believe this could be related to the following code in `lib/Loader.php`
```
* @return \Twig\Environment
--
152 | */
153 | public function get_twig() {
154 | $loader = $this->get_loader();
155 | $params = array('debug' => WP_DEBUG, 'autoescape' => false);
156 | if ( isset(Timber::$autoescape) ) {
157 | $params['autoescape'] = Timber::$autoescape === true ? 'html' : Timber::$autoescape;
```
The `debug` parameter is expected to be a `(bool)` I think if you perform as cast `array('debug' => (bool) WP_DEBUG, 'autoescape' => false)` that will fix this issue.

**Comment by windycitymoon** [comment]
Having the same issue.  WSOD when WP_DEBUG is set to false.  Works as expected when debugging set to true.

**Comment by jarednova** [comment]
@timnolte @windycitymoon @kmonahan. I wasn't able to replicate the issue on my local, but I don't doubt it's happening in your setups. Can you replace `Loader::get_twig` with this to see if it resolves the WSOD? 

```php
	/**
	 * @return \Twig_Environment
	 */
	public function get_twig() {
		$WP_DEBUG = false;
		if ( defined('WP_DEBUG') ) {
			$WP_DEBUG = (bool) WP_DEBUG;
		}
		$loader = $this->get_loader();
		$params = array('debug' => $WP_DEBUG, 'autoescape' => false);
		if ( isset(Timber::$autoescape) ) {
			$params['autoescape'] = Timber::$autoescape === true ? 'html' : Timber::$autoescape;
		}
		if ( Timber::$cache === true ) {
			Timber::$twig_cache = true;
		}
		if ( Timber::$twig_cache ) {
			$twig_cache_loc = apply_filters('timber/cache/location', TIMBER_LOC.'/cache/twig');
			if ( !file_exists($twig_cache_loc) ) {
				mkdir($twig_cache_loc, 0777, true);
			}
			$params['cache'] = $twig_cache_loc;
		}
		$twig = new \Twig_Environment($loader, $params);
		if ( $WP_DEBUG ) {
			$twig->addExtension(new \Twig_Extension_Debug());
		}
		$twig->addExtension($this->_get_cache_extension());

		$twig = apply_filters('twig_apply_filters', $twig);
		$twig = apply_filters('timber/twig/filters', $twig);
		$twig = apply_filters('timber/twig/functions', $twig);
		$twig = apply_filters('timber/twig/escapers', $twig);
		$twig = apply_filters('timber/loader/twig', $twig);
		return $twig;
	}
```

**Comment by windycitymoon** [comment]
Unfortunately, this fix didn't resolve the issue for me,  @jarednova. Same issue.

**Comment by jarednova** [comment]
Blast! Okay, I'll keep drilling ...

**Comment by jarednova** [comment]
So, I've been unable to recreate the issue even after trying a few alternate setups. I think things boil down to either ...

A) There's something in Timber with how `WP_DEBUG` is handled or interpreted as a boolean
B) There's something in `Twig\Environment` that's incorrectly handling the `debug = false` (or no/null value) that's screwing things up.

Would love any help from @windycitymoon @timnolte @kmonahan or anyone else who's encountering a WSOD! Hopefully it's a pretty light fix to get things back

**Comment by kmonahan** [comment]
Spun up a new test site with no plugins installed other than Timber and spent some time chasing down where the issue is occurring. I think I finally found it. If you follow the chain of render calls to render a Twig template, you eventually end up at /vendor/twig/twig/src/Template.php, lines 428-432, which looks like this:

```
if ($this->env->isDebug()) {
            ob_start();
        } else {
            ob_start(function () { return ''; });
        }
```
Since the Twig isDebug() value is set to WP_DEBUG by Timber, if debug is not enabled, ob_start is called with a callback that returns an empty string every time. If I replace that line with ob_start() without the callback, I no longer get a WSOD.

It's not at all clear to me why output would be discarded if isDebug is false, but it looks like that same pattern is used in the renderParentBlock() method as well in the same file. Thus, I'm wondering if isDebug should always be set to true regardless of the WP_DEBUG value within Timber's get_twig() method.  (line 155 of Loader.php)

**Comment by jarednova** [comment]
You're a hero @kmonahan — I'll do some looking through the commits/blames to figure out why that is. But in theory, we should be close to a resolution

**Comment by jarednova** [comment]
Looks like it was changed in this commit going back to 2013 .... https://github.com/timber/timber/commit/7236574c45b7a8903e0a6102a1e63a8df06b461f

**Comment by kmonahan** [comment]
This looks like a relatively recent change to Twig: https://github.com/twigphp/Twig/commit/6196fe5b40d3df385d07a5a7fd54ddde9f6bc6c4#diff-867a12ec0d98be590aa6603300a88e9e and https://github.com/twigphp/Twig/commit/c910e71f5a242e48303b5afe0535552f3dec79d2#diff-867a12ec0d98be590aa6603300a88e9e.

That explains why it's only an issue from 1.11 forward, when Twig was updated.

**Comment by jarednova** [comment]
Yeah, looks like the originating issue is here:
https://github.com/twigphp/Twig/pull/3058

Which lead to this PR by @lyrixx:
https://github.com/twigphp/Twig/pull/3059

**Comment by jarednova** [comment]
@kmonahan can you check to see what version of Twig is running in your WSOD repos? Reading through the tickets, it would seem that the recent patch _should_ fix the error (based on #3058), but that seems at odds with your direct experience.

@lyrixx — in case you're out there, I'd love any insight you could lend in what you think is going on. While in #2102 we sorta hack our way out of this, it doesn't feel like a true solve.

**Comment by kmonahan** [comment]
@jarednova,
I don't think twigphp/Twig#3059 fixes the WSOD issue. That PR changes Twig not to clear the PHP buffer when debug is TRUE, but not when debug is FALSE, which is the issue I'm hitting, where nothing displays unless WP_DEBUG is set to TRUE (since the value of debug in Twig is the same value as WP_DEBUG). It fixes an earlier issue in Twig where apparently nothing was being displayed regardless of the debug value, but it's already in place in the repos where I'm hitting WSOD.

**Comment by kmonahan** [comment]
Haven't tested very thoroughly, but this seems to work on my local with WP_DEBUG set to false:

In Loader.php, change line 74 from `$output = $twig->render($file, $data);` to:
```
$template = $twig->load($file);
$output = $template->display($data);
```

The display() method on the Template is ultimately what the render() method calls, but without the flushing of the output buffer:
```
try {
            $this->display($context);
        } catch (\Exception $e) {
            while (ob_get_level() > $level) {
                ob_end_clean();
            }

            throw $e;
        }
```

**Comment by jarednova** [comment]
cool, thanks @kmonahan. That fix seems much lighter — I'm giving that a test on #2102

**Comment by benbranyon** [comment]
Thanks @kmonahan that patch seems to work for me.

**Comment by jarednova** [comment]
@kmonahan @benbranyon thanks all! I merged in #2102 — I'll release it as a new version early next week!

**Comment by timnolte** [comment]
This seems to have come up again.

**Comment by jarednova** [comment]
@timnolte can you file a fresh ticket with all your details? I want to make sure I isolate the conditions correctly so I can replicate the specific error you're seeing

**Comment by andreanovix** [comment]
Hi, has the "Display" solution been approved? Because even with the version installed in 2022 there is always the same problem, is it possible to create a fix for this issue?

**Comment by andreanovix** [comment]
Hi, to date the problem persists, are you able to merge this request?
